# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,5)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
another_random_tensor = torch.rand(5,5)
# Perform matrix multiplication 
torch.matmul(random_tensor,another_random_tensor)

tensor([[1.6799, 1.5259, 1.7750, 1.8996, 1.5109],
        [1.0146, 0.9146, 1.0991, 1.1696, 0.9263],
        [0.7635, 0.7534, 0.7543, 0.9638, 0.9329],
        [1.1478, 0.9480, 1.2399, 1.4868, 1.2420],
        [0.9152, 0.7730, 0.9835, 0.7736, 0.5566],
        [1.1031, 0.9769, 1.2714, 1.5148, 0.9855],
        [1.0260, 0.7781, 1.1577, 1.6830, 1.0035]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [33]:
# Set manual seed
RANDOM_SEED = 73
torch.manual_seed(seed=RANDOM_SEED)
# Create two random tensors
random_tensor_one = torch.rand(3,2)
torch.manual_seed(seed=RANDOM_SEED)
random_seed_two = torch.rand(2,3)
random_tensor_two = torch.rand(2,3)
# Matrix multiply tensors
torch.matmul(random_tensor_one,random_tensor_two)

tensor([[0.1496, 0.5601, 0.2688],
        [0.3164, 1.2560, 0.7988],
        [0.0824, 0.3839, 0.3920]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [37]:
# Set random seed on the GPU
torch.cuda.manual_seed(73)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [41]:
# Set random seed
torch.manual_seed(73)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
gpu_tensor_one = torch.rand(2,3).to(device)
gpu_tensor_two = torch.rand(3,2).to(device)
print(gpu_tensor_one)
print(gpu_tensor_two)

tensor([[0.5286, 0.1616, 0.8870],
        [0.6216, 0.0459, 0.3856]], device='cuda:0')
tensor([[0.2258, 0.7837],
        [0.2052, 0.1868],
        [0.9023, 0.9923]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [55]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(gpu_tensor_one,gpu_tensor_two)
result, result.shape

(tensor([[0.9528, 1.3246],
         [0.4977, 0.8783]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [49]:
# Find max
print(f'Max: {result.max()}')
# Find min
print(f'Min: {result.min()}')

Max: 1.3246104717254639
Min: 0.49770379066467285


### 9. Find the maximum and minimum index values of the output of 7.

In [53]:
# Find arg max
print(f'Max index: {result.argmax()}')

# Find arg min
print(f'Min index: {result.argmin()}')

Max index: 1
Min index: 2



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [61]:
# Set seed
torch.manual_seed(73)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor, random_tensor.shape, squeezed, squeezed.shape

(tensor([[[[0.5286, 0.1616, 0.8870, 0.6216, 0.0459, 0.3856, 0.2258, 0.7837,
            0.2052, 0.1868]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5286, 0.1616, 0.8870, 0.6216, 0.0459, 0.3856, 0.2258, 0.7837, 0.2052,
         0.1868]),
 torch.Size([10]))